# Generated by Django 4.0.4 on 2022-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='-', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
