# Generated by Django 4.0.4 on 2022-06-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
