# Generated by Django 4.0.4 on 2022-05-19 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(max_length=255, upload_to='user/photos/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photobatl', verbose_name='Фото')),
                ('photo_name', models.CharField(max_length=255, verbose_name='Имя фото')),
                ('photo_content', models.TextField(verbose_name='Описание фото')),
                ('date_published_on_site', models.DateField(verbose_name='Дата публикации')),
                ('like_count', models.IntegerField(default=0, verbose_name='Лайки')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Комментарии')),
                ('moderation', models.BooleanField(verbose_name='Одобрено модератором')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
