# Generated by Django 4.0.4 on 2022-05-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
