# Generated by Django 4.0.4 on 2022-05-21 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
