# Generated by Django 4.0.4 on 2022-05-19 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0002_alter_user_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_published_on_site',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
    ]
