# Generated by Django 4.0.4 on 2022-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0003_alter_photo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобренно')], max_length=1),
        ),
    ]
