# Generated by Django 4.0.4 on 2022-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0003_alter_photo_date_published_on_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_published_on_site',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
