# Generated by Django 4.0.4 on 2022-05-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0004_alter_photo_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_published_on_site',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('1', 'На удалении'), ('2', 'На модерации'), ('3', 'Одобренно')], max_length=1, verbose_name='Статус'),
        ),
    ]
