# Generated by Django 4.0.4 on 2022-06-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0005_alter_comment_date_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='comment_count',
        ),
    ]
