# Generated by Django 4.0.4 on 2022-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0006_alter_photo_date_published_on_site_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_published_on_site',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
