# Generated by Django 4.0.4 on 2022-07-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='like_count',
        ),
    ]
