# Generated by Django 4.0.4 on 2022-05-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0007_alter_photo_date_published_on_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_published_on_site',
            field=models.DateField(max_length=300, verbose_name='Дата публикации'),
        ),
    ]
