# Generated by Django 4.0.4 on 2022-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0008_alter_photo_date_published_on_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_published_on_site',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=300, upload_to='photobatl/photos/', verbose_name='Фото'),
        ),
    ]
