# Generated by Django 4.0.6 on 2022-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0009_rename_user_name_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('DEL', 'На удалении'), ('MOD', 'На модерации'), ('APR', 'Одобренно'), ('REJ', 'Отклоненно')], default='MOD', max_length=3, verbose_name='Статус'),
        ),
    ]
