# Generated by Django 4.1 on 2022-09-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0011_photo_previous_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='previous_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Предыдущее фото'),
        ),
    ]
