# Generated by Django 4.1 on 2022-09-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0012_alter_photo_previous_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='task_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
