# Generated by Django 4.1.3 on 2022-11-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0013_photo_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата обновления'),
        ),
    ]
