# Generated by Django 4.1.3 on 2022-11-22 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0014_alter_photo_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='published_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
