# Generated by Django 4.1.3 on 2022-11-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0015_photo_published_at_alter_photo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='published_at',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
    ]
