# Generated by Django 4.1.3 on 2022-11-30 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0016_alter_photo_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Like'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Photo'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=300, verbose_name='Comment content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of create'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='photobatle.comment', verbose_name='Parent of comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_photo', to='photobatle.photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_photo', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_photo', to='photobatle.photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_like', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of create'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='moderation',
            field=models.CharField(choices=[('DELETION', 'On deletion'), ('MODERATION', 'On moderation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='MODERATION', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=300, upload_to='photobatl/photos/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_content',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='previous_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Previous file'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published_at',
            field=models.DateField(null=True, verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name_username', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(max_length=255, upload_to='user/photos/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('photo', 'user')},
        ),
    ]
