# Generated by Django 4.1.3 on 2022-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0017_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
