# Generated by Django 4.1.4 on 2022-12-06 12:57

from django.db import migrations
import django_counter_cache_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photobatle', '0018_alter_photo_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comment_count',
            field=django_counter_cache_field.fields.CounterCacheField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='like_count',
            field=django_counter_cache_field.fields.CounterCacheField(default=0),
        ),
    ]
