from .PhotoService.AddPhoto import *
from .PhotoService.UpdatePhoto import *
from .PhotoService.DeletePhoto import *
from .PhotoService.RecoveryPhoto import *
from .LikeService.CreateLike import *
from .LikeService.DeleteLike import *
from .CommentService.CreateComment import *
from .CommentService.DeleteComment import *
from .CommentService.UpdateComment import *
from .AjaxService.SortingForm import *
from .AjaxService.SearchForm import *
from .AjaxService.PersonalSortingForm import *
