from api.custom_schema.user.get import *
from api.custom_schema.photo.general.getPhotos import *
from api.custom_schema.photo.get import *
from api.custom_schema.photo.delete import *
from api.custom_schema.photo.patch import *
from api.custom_schema.photo.post import *
from api.custom_schema.photo.personal.getPhotos import *
from api.custom_schema.comment.post import *
from api.custom_schema.comment.patch import *
from api.custom_schema.comment.delete import *
from api.custom_schema.like.post import *
from api.custom_schema.like.delete import *
