from api.custom_schema.user.get import *
from api.custom_schema.photo.get import *
from api.custom_schema.photo.delete import *
from api.custom_schema.photo.patch import *
from api.custom_schema.photo.post import *
from api.custom_schema.personal_photo.get import *
from api.custom_schema.sort_photo.get import *
from api.custom_schema.sort_personal_photo.get import *
from api.custom_schema.comment.post import *
from api.custom_schema.comment.patch import *
from api.custom_schema.comment.delete import *
