from api.custom_schema.user.show import *
from api.custom_schema.photo.general.index import *
from api.custom_schema.photo.show import *
from api.custom_schema.photo.delete import *
from api.custom_schema.photo.patch import *
from api.custom_schema.photo.post import *
from api.custom_schema.photo.personal.index import *
from api.custom_schema.comment.post import *
from api.custom_schema.comment.patch import *
from api.custom_schema.comment.delete import *
from api.custom_schema.like.post import *
